name         'gsick-redis'
version      '0.0.5'
source       'https://github.com/gsick/puppet-redis.git'
author       'Gamaliel Sick'
license      'MIT'
summary      'Redis installation and configuration module'
description  'Puppet module for installing and configuring Redis'
project_page 'https://github.com/gsick/puppet-redis'

dependency   'puppetlabs/stdlib', '>= 4.2.2'
